Update patch set 6
Patch Set 6:

Tony, I do not see any differrent access in the code in your PR. Do you perhaps mean the special requirements.txt line for helm?

That's there because cloudify(-common)-5.0.5.1 doesn't actually run in python3 the incompatibilities are all over cloudify, including syntax errors. Only the helm test does import a module which breaks (imports StringIO from the old module). In fact, I doubt any of the plugins would really work with 5.0.5.1 when everything were to run in python3, even if the tests here don't uncover that.

E.g.

(py3cloudify) mirlos@panbuntu:~/pjs/onapx/to3/py3cloudify$ pip list | grep -e cloudify 
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
cloudify (5.0.5.1)
cloudify-common (5.0.5.1)
(py3cloudify) mirlos@panbuntu:~/pjs/onapx/to3/py3cloudify$ ctx
Traceback (most recent call last):
  File "/home/mirlos/pjs/onapx/to3/py3cloudify/bin/ctx", line 7, in <module>
    from cloudify.proxy.client import main
  File "/home/mirlos/pjs/onapx/to3/py3cloudify/lib/python3.6/site-packages/cloudify/proxy/client.py", line 18, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
(py3cloudify) mirlos@panbuntu:~/pjs/onapx/to3/py3cloudify$ cfy
Traceback (most recent call last):
  File "/home/mirlos/pjs/onapx/to3/py3cloudify/bin/cfy", line 11, in <module>
    load_entry_point('cloudify==5.0.5.1', 'console_scripts', 'cfy')()
  File "/home/mirlos/pjs/onapx/to3/py3cloudify/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mirlos/pjs/onapx/to3/py3cloudify/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/mirlos/pjs/onapx/to3/py3cloudify/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/mirlos/pjs/onapx/to3/py3cloudify/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mirlos/pjs/onapx/to3/py3cloudify/lib/python3.6/site-packages/cloudify_cli/main.py", line 18, in <module>
    from .cli import cfy
  File "/home/mirlos/pjs/onapx/to3/py3cloudify/lib/python3.6/site-packages/cloudify_cli/cli/cfy.py", line 21, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'


I still maintain this PR is more polished than the other one. It's up to the long-term developers though.

Patch-set: 6
Reviewer: Gerrit User 6172 <6172@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0